import {Food} from './app/shared/models/Food';

export const sample_foods: Food[] = [
  {
    id:'1',
    name: 'Fish Meat Siu Mai',
    price: 20,
    cooktime: '10-15',
    favorite: true,
    origins: ['China'],
    stars: 5,
    imageUrl: 'assets/food-1.png',
    tags: ['SlowFood','DimSum', 'Breakfast'],
  },
  {
    id:'2',
    name: 'Pizza',
    price: 80,
    cooktime: '30',
    favorite: false,
    origins: ['italy'],
    stars: 3.5,
    imageUrl: 'assets/food-2.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'3',
    name: 'Sushi',
    price: 18,
    cooktime: '5',
    favorite: true,
    origins: ['japan'],
    stars: 4.0,
    imageUrl: 'assets/food-3.jpg',
    tags: ['SlowFood', 'Sushi'],
  },
  {
    id:'4',
    name: 'Spaghetti',
    price: 50,
    cooktime: '30',
    favorite: false,
    origins: ['italy'],
    stars: 3.8,
    imageUrl: 'assets/food-4.jpg',
    tags: ['SlowFood', 'Spaghetti'],
  },
  {
    id:'5',
    name: 'Egg Cake',
    price: 10,
    cooktime: '5',
    favorite: false,
    origins: ['Taiwan', 'asia'],
    stars: 3.0,
    imageUrl: 'assets/food-5.jpg',
    tags: ['FastFood', 'Egg', 'Cake'],
  },
  {
    id:'6',
    name: 'Chow Mein',
    price: 15,
    cooktime: '40-50',
    favorite: false,
    origins: ['China','asia'],
    stars: 4.3,
    imageUrl: 'assets/food-6.jpg',
    tags: ['SlowFood', 'Fry'],
  },
]
